language: node_js
node_js:
  - "stable"
addons:
  apt:
      packages:
        - aspell
        - aspell-en
script:
  - yarn run spell
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: build
  target-branch: master
  on:
    branch: development
after_deploy:
  - |
    curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
     -H "X-Auth-Email: $CLOUDFLARE_EMAIL"\
     -H "X-Auth-Key: $CLOUDFLARE_AUTH_KEY"\
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}' && echo 'Cloudflare Cache... Purged.'
